Register page
Bockkwurst/ToDoList-Frontend pull request #17
Opened 2024-06-05 12:40 UTC by Bockkwurst

2024-06-06 07:35 UTC, LH311299 approved these changes

2024-06-06 08:45 UTC, LH311299 approved these changes

2024-06-10 08:49 UTC, marinus-g requested changes

2024-06-10 08:49 UTC, marinus-g commented on todolist/src/App.jsx
> +        ;
:( MACH DAS SEMIKOLON EINE ZEILE HÖHER

2024-06-10 08:54 UTC, marinus-g approved these changes

2024-06-10 08:54 UTC, merged